name: Bug Report
description: Create a report to help us improve Android Volume Controller
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees:
  - y4kupkaya

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛
        
        Please search existing issues before creating a new one to avoid duplicates.

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Android Volume Controller are you using?
      placeholder: v1.0.0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Open Windows Volume Mixer
        2. Adjust Android device volume slider
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen.
      placeholder: Android device volume should change accordingly...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear description of what actually happened.
      placeholder: Instead, the volume remains unchanged and shows error...
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which Windows version are you using?
      options:
        - Windows 11
        - Windows 10
        - Other (please specify in additional context)
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: 3.9.7
    validations:
      required: true

  - type: input
    id: android-device
    attributes:
      label: Android Device
      description: What Android device are you using?
      placeholder: Samsung Galaxy S21, Android 12
    validations:
      required: true

  - type: dropdown
    id: adb-status
    attributes:
      label: ADB Status
      description: Can you connect to your device with ADB?
      options:
        - "Yes, adb devices shows my device"
        - "No, adb devices shows no devices"
        - "I haven't checked"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Log Output
      description: |
        Please paste any relevant log output here. 
        Run the application with verbose logging if possible.
      render: shell
      placeholder: |
        Paste log output here...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here.
        Screenshots, error messages, or other relevant information.
      placeholder: Any additional information that might help...

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I have provided all required information above
          required: true
        - label: I am using a supported version of the application
          required: true